name: deti_azii
description: app for children of asia sport.
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_native_splash: ^2.3.4
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  http: ^1.1.0
  latlong2: ^0.9.0
  mobile_scanner: ^3.4.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/minilogo.png"