name: peakit_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  flutter_native_splash: ^2.3.4
  http: ^1.1.0
  latlong2: ^0.9.0
  webview_flutter: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/minilogo.png"